#!/bin/bash

cd /etc/pki/tls/certs;
/usr/bin/openssl req -utf8 -subj "/C=GB/ST=Auto/L=Cert/O=Dis/CN=replaceme.com"  -newkey rsa -keyout sendmail.pem  -nodes -x509 -days 3650 -out sendmail.pem 
chmod 500 sendmail.pem

cd /
if [ ! -f /etc/mail/sendmail.mc ]; then 
	tar -xzvf /root/etc_mail.tgz 
fi
rm -f /root/etc_mail.tgz

systemctl disable runonce
