#!/bin/bash

cd /etc/pki/tls/certs;
/usr/bin/openssl req -utf8 -subj "/C=GB/ST=Auto/L=Cert/O=Dis/CN=replaceme.com"  -newkey rsa -keyout sendmail.pem  -nodes -x509 -days 3650 -out sendmail.pem 
chmod 500 sendmail.pem

cd /
if [ ! -f /etc/mail/sendmail.mc ]; then 
	tar -xzvf /root/etc_mail.tgz 
fi
rm -f /root/etc_mail.tgz

if [ -n "${MAIL_UID:-}" ]; then
	usermod --uid $MAIL_UID mail
fi

if [ -n "${MAIL_GID:-}" ]; then
	groupmod --gid $MAIL_GID mail
fi

systemctl disable runonce
